# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true
plugins:          [jekyll-paginate, redcarpet, pygments.rb]

# Setup
title:            Amrita
tagline:          'V proudu energie života'
description:      'Prostor sebepoznání a harmonie v Orlických horách.'
url:              http://www.amrita.cz
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde


blog:
  url:            /blog

kontakt:
  url:            /kontakt

akce:
  url:            /akce
