# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true
plugins:          [jekyll-paginate, redcarpet, pygments.rb]

# Setup
title:            Amrita
tagline:          'V proudu energie života'
description:      'Prostor sebepoznání a harmonie v Orlických horách.'
url:              http://www.amrita.cz
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

defaults:
  - scope:
      path:       "public/gallery/images"
    values:
      gallery_image:      true

  - scope:
      path:       "public/gallery/images"
    values:
      gallery_thumbnail:      true

defaults:
  - scope:
      path:       "public/neberybka_gallery/images"
    values:
      neberybka_gallery_image:      true

urls:
  blog:           /blog
  contact:        /kontakt
  events:         /akce
  people:         /lide
  gallery:        /galerie
  staying:        /pobyvani
  neberybka:        /neberybka
