# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true
plugins:          [jekyll-paginate, redcarpet, pygments.rb]

# Setup
title:            Neberybka
tagline:          'V proudu energie života'
description:      'Prostor sebepoznání a harmonie v Orlických horách.'
url:              http://www.neberybka.cz
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

defaults:
  - scope:
      path:       "public/gallery/images"
    values:
      gallery_image:      true

  - scope:
      path:       "public/neberybka_gallery/images"
    values:
      neberybka_gallery_image:      true

urls:
  kontakt:        /kontakt
  akce:           /akce
  lide:           /lide
  galerie:        /galerie
  pobyvani:       /pobyvani
  prostor:        /prostor
